# This is a basic workflow to help you get started with Actions
name: Flutter CI CD

# Controls when the workflow will run
on: # Triggers the workflow on pull or push for the "main" branch

  pull_request:
    branches: [ 'master' ]

  push:
    branches: [ 'master' ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Set Up Java JDK
      - name: Set up JAVA JDK
        uses: actions/setup-java@v4.0.0

        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      # Flutter environment for use in GitHub Actions
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true
            
      # Get dependencies of flutter
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk --no-tree-shake-icons

      # Uploading the build on GitHub
      - name: Upload the build
        uses: actions/upload-artifact@v4.0.0
        with:
          name: CI CD Build
          path: build/app/outputs/apk/release/app-release.apk



